version: 2
build:
  os: ubuntu-20.04
  tools:
    python: miniconda3-3.12-24.1
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - method: setuptools
    path: .
conda:
  environment: docs/environment.yml
formats:
- pdf
