# Configuration for codecov.io
# When editing this file, please validate its contents using:
#   curl -X POST --data-binary @- https://codecov.io/validate < codecov.yml
codecov:
  branch: main
  require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff, changes, uncovered
  require_base: false
  require_changes: false
  require_head: true
coverage:
  precision: 2
  round: down
  status:
    changes: false
    project:
        default:
            informational: true
    patch:
      default:
        target: auto
        threshold: 10%
        base: auto 
