#!/usr/bin/env python
### Copyright (2012) Continuum Analytics, Inc
### All Rights Reserved

"""
  pycc --- python compiler
  Produce a shared library from Python code

  Usage:  pycc <input-py-file(s)> -o output-file

  Compile input files to a single shared library (final step uses the platform
  linker which must be installed).

  Options:
             -h  Help
             -o  Name of output file (default is name of first input -- with new ending)
             -c  Create object code from each input file instead of shared library
             --llvm Emit llvm module instead of object code
             --linker path-to-linker (if not on $PATH and llvm not provided)
             --linker-args string of args (be sure to use quotes)
             --headers output equivalent C-header files
"""

from numba.pycc.pycc import main
main()