parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py27_np15:
        PYTHON: '2.7'
        NUMPY: '1.15' 
        CONDA_ENV: 'testenv'
      py37_np15:
        PYTHON: '3.7'
        NUMPY: '1.15' 
        CONDA_ENV: 'testenv'

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''

    # Need to install VC 9.0 only for Python 2.7
    - powershell: |
        $wc = New-Object net.webclient
        $wc.Downloadfile("https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi", "VCForPython27.msi")
        Start-Process "VCForPython27.msi" /qn -Wait
      displayName: 'Install VC 9.0'
      condition: eq(variables['PYTHON'], '2.7')

    - script: |
        buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    # VC 9.0 cannot build tbbpool.cpp in Numba, so we need to remove
    # tbb from the environment before the build stage.
    - script: |
        call activate %CONDA_ENV%
        conda remove -y tbb tbb-devel
      displayName: 'Remove TBB'
      condition: eq(variables['PYTHON'], '2.7')

    - script: |
        buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        # One of the tbb tests is failing on Azure.  Removing tbb before
        # testing until we can figure out why.  Only do this for Python 3
        # because we already removed TBB before build on Python 2.
        call activate %CONDA_ENV%
        conda remove -y tbb tbb-devel
      displayName: 'Remove TBB'
      condition: ne(variables['PYTHON'], '2.7')

    - script: |
        call activate %CONDA_ENV%
        pushd bin
        numba -s
        popd
        python -m numba.tests.test_runtests
        python runtests.py -m 2 -b -- numba.tests
      displayName: 'Test'
