parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_np121:
        PYTHON: '3.8'
        NUMPY: '1.21'
        CONDA_ENV: 'testenv'
        TEST_START_INDEX: 18
      py311_np124:
        PYTHON: '3.11'
        NUMPY: '1.24'
        CONDA_ENV: 'testenv'
        TEST_START_INDEX: 19

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''

    - script: |
        buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    - script: |
        buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        call activate %CONDA_ENV%
        python -m numba -s
      displayName: 'Display numba system information'

    - script: |
        call activate %CONDA_ENV%
        python -m numba.tests.test_runtests
      displayName: 'Verify runtests'

    - script: |
        call activate %CONDA_ENV%
        set NUMBA_ENABLE_CUDASIM=1
        python -m numba.runtests -l
      displayName: 'List discovered tests'

    - script: |
        call activate %CONDA_ENV%
        set NUMBA_CAPTURED_ERRORS=new_style
        set NUMBA_ENABLE_CUDASIM=1
        echo "Running shard of discovered tests: %TEST_START_INDEX%,None,%TEST_COUNT%"
        python -m numba.runtests -b -v -g -m 2 -- numba.tests
      displayName: 'Test modified test files'

    - script: |
        call activate %CONDA_ENV%
        set NUMBA_CAPTURED_ERRORS=new_style
        set NUMBA_ENABLE_CUDASIM=1
        echo "Running shard of discovered tests: %TEST_START_INDEX%:%TEST_COUNT%"
        python runtests.py -m 2 -b -j "%TEST_START_INDEX%:%TEST_COUNT%"  --exclude-tags='long_running'  -- numba.tests
      displayName: 'Test shard of test files'
