parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_np118:
        PYTHON: '3.8'
        NUMPY: '1.18'
        CONDA_ENV: 'testenv'
        TEST_START_INDEX: 16
      py37_np115:
        PYTHON: '3.7'
        NUMPY: '1.15'
        CONDA_ENV: 'testenv'
        TEST_START_INDEX: 17

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''

    - script: |
        buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    - script: |
        # use TBB
        call activate %CONDA_ENV%
        conda install -y tbb tbb-devel
      displayName: 'Add in TBB'

    - script: |
        buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        call activate %CONDA_ENV%
        python -m numba -s
      displayName: 'Display numba system information'

    - script: |
        call activate %CONDA_ENV%
        python -m numba.tests.test_runtests
      displayName: 'Verify runtests'

    - script: |
        call activate %CONDA_ENV%
        python -m numba.runtests -l
      displayName: 'List discovered tests'

    - script: |
        call activate %CONDA_ENV%
        echo "Running slice of discovered tests: %TEST_START_INDEX%,None,%TEST_COUNT%"
        python -m numba.runtests -b -v -g -m 2 -- numba.tests
      displayName: 'Test modified test files'

    - script: |
        call activate %CONDA_ENV%
        python runtests.py -m 2 -b -j "%TEST_START_INDEX%,None,%TEST_COUNT%"  --exclude-tags='long_running'  -- numba.tests
      displayName: 'Test slice of test files'
