parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: |
        if [ "$(uname)" == "Linux" ] && [[ "$CONDA_SUBDIR" == "linux-32" || "$BITS32" == "yes" ]]; then sudo apt-get install -y libc6-dev-i386; fi
        if [ "$(uname)" == "Linux" ] && [[ "$CONDA_SUBDIR" != "linux-32" && "$BITS32" != "yes" ]]; then sudo apt-get install -y gdb; fi
        echo "Installing Miniconda"
        buildscripts/incremental/install_miniconda.sh
        export PATH=$HOME/miniconda3/bin:$PATH
        echo "Setting up Conda environment"
        buildscripts/incremental/setup_conda_environment.sh
      displayName: 'Before Install'

    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        buildscripts/incremental/build.sh
      displayName: 'Build'

    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        conda install -y flake8
        flake8 numba
      displayName: 'Flake8'
      condition: eq(variables['RUN_FLAKE8'], 'yes')

    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        conda install -y mypy
        mypy
      displayName: 'Mypy'
      condition: eq(variables['RUN_MYPY'], 'yes')

    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        buildscripts/incremental/test.sh
      displayName: 'Test'
