package:
  name: numba
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/numba/numba

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - python
    - numpy x.x
    # On channel https://anaconda.org/numba/
    - llvmlite 0.16.*
    - funcsigs       [py27]
    - singledispatch [py27]
  run:
    - python
    - numpy x.x
    # On channel https://anaconda.org/numba/
    - llvmlite 0.16.*
    - funcsigs       [py27]
    - singledispatch [py27]
test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython
  files:
    - mandel.py
  commands:
    # Check Numba executables are there
    - pycc -h
    - numba -h
    # run system info tool
    - numba -s
    # Check test discovery works
    - python -m numba.tests.test_runtests
    # Run the whole test suite
    - python -m numba.runtests -m -b
about:
  home: http://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
