from typing import overload
import numpy as np

@overload
def prange(stop: int, /) -> range: ...
@overload
def prange(start: int, stop: int, /) -> range: ...
@overload
def prange(start: int, stop: int, step: int, /) -> range: ...

def pndindex(*args: int) -> np.ndindex: ...

