package:
  name: numba-hsa
  version: 0.21.0

source:
  path: ../..

build:
  number: 0
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - python
    - numpy x.x
    # On channel https://binstar.org/numba/
    - llvmlite 0.24.*
    - funcsigs       [py27]
    - singledispatch [py27]
  run:
    - python
    - numpy x.x
    # On channel https://binstar.org/numba/
    - llvmlite 0.24.*
    - funcsigs       [py27]
    - singledispatch [py27]
    - libhlc
test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython
  files:
    - mandel.py
  commands:
    # Check Numba executables are there
    - pycc -h
    - numba -h
    # run system info tool
    - numba -s
    # Check test discovery works
    - NUMBA_DEVELOPER_MODE=1 NUMBA_DISABLE_ERROR_MESSAGE_HIGHLIGHTING=1 python -m numba.tests.test_runtests
about:
  home: http://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
