package:
   name: numba
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main
  script_env:
    - PY_VCRUNTIME_REDIST
  missing_dso_whitelist: # [osx]
    # optional dependency: required only when omp is chosen as the backend for
    # the threading layer
    - lib/libiomp5.dylib # [osx]

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - {{ compiler('c') }}      # [not (armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }}    # [not (armv6l or armv7l or aarch64)]
    # both of these are needed on osx, llvm for the headers, Intel for the lib
    - llvm-openmp              # [osx]
    - intel-openmp             # [osx]
  host:
    - python
    - numpy x.x
    - setuptools
    # On channel https://anaconda.org/numba/
    - llvmlite 0.30.*
    - funcsigs                 # [py27]
    - singledispatch           # [py27]
    # TBB devel version is to match TBB libs
    - tbb-devel >=2018.0.5     # [not ((armv6l or armv7l or aarch64) or (win and py27))]
  run:
    - python
    - numpy x.x
    # On channel https://anaconda.org/numba/
    - llvmlite 0.30.*
    - funcsigs                 # [py27]
    - singledispatch           # [py27]
  run_constrained:
    # If TBB is present it must be at least this version from Anaconda due to
    # build flag issues triggering UB
    - tbb >=2018.0.5           # [not ((armv6l or armv7l or aarch64) or (win and py27))]
    # avoid confusion from openblas bugs
    - libopenblas !=0.3.6      # [x86_64]
test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    # temporarily disable scipy testing on ARM, need to build out more packages
    - scipy                    # [not (armv6l or armv7l)]
    - ipython                  # [not (armv6l or armv7l or aarch64)]
    - setuptools
    - faulthandler             # [py27 and (not (armv6l or armv7l or aarch64))]
    - tbb  >=2018.0.5          # [not ((armv6l or armv7l or aarch64) or (win and py27))]
    - intel-openmp             # [osx]
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not (win or armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }}    # [not (win or armv6l or armv7l or aarch64)]
  files:
    - mandel.py

about:
  home: http://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
