package:
   name: numba
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ NPY_VER }}py{{ PY_VER }}h{{ PKG_HASH }}_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.misc.numba_entry:main
  script_env:
    - PY_VCRUNTIME_REDIST
  missing_dso_whitelist: # [osx]
    # optional dependency: required only when omp is chosen as the backend for
    # the threading layer
    - lib/libiomp5.dylib # [osx]
  ignore_run_exports:
    # tbb-devel triggers hard dependency on tbb, this is not the case.
    - tbb     # [not (armv6l or armv7l or aarch64 or linux32)]

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - {{ compiler('c') }}      # [not (armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }}    # [not (armv6l or armv7l or aarch64)]
    # OpenMP headers from llvm needed for OSX.
    - llvm-openmp              # [osx]
  host:
    - python
    - numpy
    - setuptools
    - importlib_metadata       # [py<39]
    # On channel https://anaconda.org/numba/
    - llvmlite >=0.39.0dev0,<0.39
    # TBB devel version is to match TBB libs.
    # 2020.3 is the last version with the "old" ABI
    # NOTE: ppc64le exclusion is temporary until packages are more generally
    #       available.
    - tbb-devel >=2021       # [not (armv6l or armv7l or aarch64 or linux32 or ppc64le)]
  run:
    - python >=3.7
    - numpy >=1.18
    - setuptools
    - importlib_metadata       # [py<39]
    # On channel https://anaconda.org/numba/
    - llvmlite >=0.39.0dev0,<0.39
  run_constrained:
    # If TBB is present it must be at least version 2021
    - tbb >=2021    # [not (armv6l or armv7l or aarch64 or linux32 or ppc64le)]
    # avoid confusion from openblas bugs
    - libopenblas !=0.3.6      # [x86_64]
    # CUDA 9.2 or later is required for CUDA support
    - cudatoolkit >=9.2
    # scipy 1.0 or later
    - scipy >=1.0
    # CUDA Python 11.6 or later
    - cuda-python >=11.6

test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    # temporarily disable scipy testing on ARM, need to build out more packages
    - scipy                    # [not (armv6l or armv7l)]
    - ipython                  # [not (armv6l or armv7l or aarch64)]
    - setuptools
    - tbb  >=2021              # [not (armv6l or armv7l or aarch64 or linux32 or ppc64le)]
    - llvm-openmp              # [osx]
    # This is for driving gdb tests
    - pexpect                  # [linux64]
    # For testing ipython
    - ipykernel
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not (win or armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }}    # [not (win or armv6l or armv7l or aarch64)]

about:
  home: https://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
