package:
   name: numba
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy x.x
    - setuptools
    # On channel https://anaconda.org/numba/
    - llvmlite 0.24.*
    - funcsigs                 # [py27]
    - singledispatch           # [py27]
  run:
    - python
    - numpy x.x
    # On channel https://anaconda.org/numba/
    - llvmlite 0.24.*
    - funcsigs                 # [py27]
    - singledispatch           # [py27]
test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython
    - setuptools
    - faulthandler             # [py27]
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('cxx') }}    # [not win]
  files:
    - mandel.py

about:
  home: http://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
