[mypy]
files = numba/**/*.pyi
exclude = (?x)(
    ^numba/(
      .+\.py$
      | tests/
    )
  )
follow_imports = silent

warn_unused_configs = True
allow_redefinition_new = True
local_partial_types = True

; TODO
ignore_errors = True

[mypy-llvmlite.*]
ignore_missing_imports = True

[mypy-graphviz.*]
ignore_missing_imports = True
