"""Enum values for HSA

Note that Python namespacing could be used to avoid the C-like
prefixing, but we choose to keep the same names as found in the C
enums, in order to match the documentation.

"""

# hsa_status_t

HSA_STATUS_SUCCESS = 0
HSA_STATUS_INFO_BREAK = 0x1
HSA_EXT_STATUS_INFO_ALREADY_INITIALIZED = 0x4000
HSA_EXT_STATUS_INFO_UNRECOGNIZED_OPTIONS = 0x4001
HSA_STATUS_ERROR = 0x10000
HSA_STATUS_ERROR_INVALID_ARGUMENT = 0x10001
HSA_STATUS_ERROR_INVALID_QUEUE_CREATION = 0x10002
HSA_STATUS_ERROR_INVALID_ALLOCATION = 0x10003
HSA_STATUS_ERROR_INVALID_AGENT = 0x10004
HSA_STATUS_ERROR_INVALID_REGION = 0x10005
HSA_STATUS_ERROR_INVALID_SIGNAL = 0x10006
HSA_STATUS_ERROR_INVALID_QUEUE = 0x10007
HSA_STATUS_ERROR_OUT_OF_RESOURCES = 0x10008
HSA_STATUS_ERROR_INVALID_PACKET_FORMAT = 0x10009
HSA_STATUS_ERROR_RESOURCE_FREE = 0x1000A
HSA_STATUS_ERROR_NOT_INITIALIZED = 0x1000B
HSA_STATUS_ERROR_REFCOUNT_OVERFLOW = 0x1000C
HSA_EXT_STATUS_ERROR_DIRECTIVE_MISMATCH = 0x14000
HSA_EXT_STATUS_ERROR_IMAGE_FORMAT_UNSUPPORTED = 0x14001
HSA_EXT_STATUS_ERROR_IMAGE_SIZE_UNSUPPORTED = 0x14002
