MATH_UNARY(sin, double, double)
MATH_UNARY(sinf, float, float)

MATH_UNARY(cos, double, double)
MATH_UNARY(cosf, float, float)

MATH_UNARY(tan, double, double)
MATH_UNARY(tanf, float, float)

MATH_UNARY(asin, double, double)
MATH_UNARY(asinf, float, float)

MATH_UNARY(acos, double, double)
MATH_UNARY(acosf, float, float)

MATH_UNARY(atan, double, double)
MATH_UNARY(atanf, float, float)

MATH_UNARY(asinh, double, double)
MATH_UNARY(asinhf, float, float)

MATH_UNARY(acosh, double, double)
MATH_UNARY(acoshf, float, float)

MATH_UNARY(atanh, double, double)
MATH_UNARY(atanhf, float, float)

MATH_UNARY(exp, double, double)
MATH_UNARY(expf, float, float)

MATH_UNARY(expm1, double, double)
MATH_UNARY(expm1f, float, float)

MATH_UNARY(sqrt, double, double)
MATH_UNARY(sqrtf, float, float)

MATH_UNARY(fabs, double, double)
MATH_UNARY(fabsf, float, float)

MATH_UNARY(floor, double, double)
MATH_UNARY(floorf, float, float)

MATH_UNARY(ceil, double, double)
MATH_UNARY(ceilf, float, float)

MATH_UNARY(log, double, double)
MATH_UNARY(logf, float, float)

MATH_UNARY(log10, double, double)
MATH_UNARY(log10f, float, float)

MATH_UNARY(log1p, double, double)
MATH_UNARY(log1pf, float, float)

MATH_BINARY(pow, double, double, double)
MATH_BINARY(powf, float, float, float)
